export default {
  "nodes": [
    { "name": "铁块" },
    { "name": "齿轮" },
    { "name": "传送带" },
    { "name": "传送带-高速" },
    { "name": "传送带-极速" },
    { "name": "电磁涡轮" },
    { "name": "超级磁场环" },
    { "name": "石墨烯" },
    { "name": "磁化电浆炮" },
    { "name": "钛合金" },
    { "name": "钛化玻璃" },
    { "name": "电浆激发器" },
    { "name": "处理器" },
    { "name": "大型采矿机" },
    { "name": "框架材料" },
    { "name": "量子芯片" },
    { "name": "光珊石" },
    { "name": "导弹防御塔" },
    { "name": "钢材" },
    { "name": "电动机" },
    { "name": "电路板" },
    { "name": "动力引擎" },
    { "name": "电弧熔炉" },
    { "name": "石材" },
    { "name": "磁线圈" },
    { "name": "磁铁" },
    { "name": "铜块" },
  ],
  "links": [
    { "source": "传送带", "target": "铁块", "value": 2 },
    { "source": "传送带", "target": "齿轮", "value": 1 },
    { "source": "传送带-高速", "target": "传送带", "value": 3 },
    { "source": "传送带-高速", "target": "电磁涡轮", "value": 1 },
    { "source": "传送带-极速", "target": "传送带-高速", "value": 3 },
    { "source": "传送带-极速", "target": "超级磁场环", "value": 1 },
    { "source": "传送带-极速", "target": "石墨烯", "value": 1 },
    { "source": "磁化电浆炮", "target": "钛合金", "value": 20 },
    { "source": "磁化电浆炮", "target": "钛化玻璃", "value": 10 },
    { "source": "磁化电浆炮", "target": "超级磁场环", "value": 10 },
    { "source": "磁化电浆炮", "target": "电浆激发器", "value": 5 },
    { "source": "磁化电浆炮", "target": "处理器", "value": 5 },
    { "source": "大型采矿机", "target": "钛合金", "value": 20 },
    { "source": "大型采矿机", "target": "框架材料", "value": 10 },
    { "source": "大型采矿机", "target": "超级磁场环", "value": 10 },
    { "source": "大型采矿机", "target": "量子芯片", "value": 4 },
    { "source": "大型采矿机", "target": "光珊石", "value": 40 },
    { "source": "钢材", "target": "铁块", "value": 3 },
    { "source": "导弹防御塔", "target": "钢材", "value": 8 },
    { "source": "导弹防御塔", "target": "电动机", "value": 6 },
    { "source": "导弹防御塔", "target": "电路板", "value": 12 },
    { "source": "导弹防御塔", "target": "动力引擎", "value": 6 },
    { "source": "电弧熔炉", "target": "铁块", value: 4 },
    { "source": "电弧熔炉", "target": "石材", value:2 },
    { "source": "电弧熔炉", "target": "电路板", value: 4},
    { "source": "电弧熔炉", "target": "磁线圈", value: 2},
    { "source": "磁线圈", "target": "磁铁", value: 2},
    { "source": "磁线圈", "target": "铜块", value: 1},
    
  ]
}


