export default {
  "nodes": [
    { "name": "铁块" },
    { "name": "齿轮" },
    { "name": "传送带", "finalTarget": true },
    { "name": "传送带-高速", "finalTarget": true },
    { "name": "传送带-极速", "finalTarget": true },
    { "name": "电磁涡轮" },
    { "name": "超级磁场环" },
    { "name": "石墨烯" },
    { "name": "磁化电浆炮", "finalTarget": true },
    { "name": "钛合金" },
    { "name": "钛化玻璃" },
    { "name": "电浆激发器", "finalTarget": true },
    { "name": "处理器" },
    { "name": "大型采矿机", "finalTarget": true },
    { "name": "框架材料" },
    { "name": "量子芯片" },
    { "name": "光珊石" },
    { "name": "导弹防御塔", "finalTarget": true },
    { "name": "钢材" },
    { "name": "电动机" },
    { "name": "电路板" },
    { "name": "动力引擎" },
    { "name": "电弧熔炉" , "finalTarget": true},
    { "name": "石材" },
    { "name": "磁线圈" },
    { "name": "磁铁" },
    { "name": "铜块" },
    { "name": "电力感应塔", "finalTarget": true },
    { "name": "分捡器" },
    { "name": "分捡器-高速" },
    { "name": "分捡器-极速" },
    { "name": "电磁涡轮" },
    { "name": "分捡器-集装" , "finalTarget": true},
    { "name": "高频激光塔", "finalTarget": true },
    { "name": "光子合并器" },
    { "name": "棱镜" },
    { "name": "化工厂" },
    { "name": "玻璃" },
    { "name": "化工厂-量子" },
    { "name": "奇异物质" },
    { "name": "钛块" },
    { "name": "水" },
    { "name": "粒子容器" },
    { "name": "重氢" },
    { "name": "微晶元件" },
    { "name": "卡西米尔晶体" },
    { "name": "聚爆加农炮", "finalTarget": true },
    { "name": "磁铁" },
    { "name": "高能石墨" },
    { "name": "碳纳米管" },
    { "name": "高纯硅块" },
    { "name": "堙灭约束球" },
    { "name": "微型粒子对撞机", "finalTarget": true },
    { "name": "射线接收站"},
    { "name": "卫星配电站", "finalTarget": true },
    { "name": "无线传输塔" , "finalTarget": true},
    { "name": "信号塔" },
    { "name": "晶格硅" },
    { "name": "行星护盾发生器", "finalTarget": true },
    { "name": "战场分析基站", "finalTarget": true },
    { "name": "制造台" , "finalTarget": true},
    { "name": "制造台-2", "finalTarget": true },
    { "name": "制造台-3", "finalTarget": true },
    { "name": "粒子宽带" },
    { "name": "钛晶石" },
    { "name": "有机晶体" },
    { "name": "位面过滤器" },
    { "name": "人造恒星" , "finalTarget": true},
    { "name": "硫酸" },
    { "name": "塑料" },
    { "name": "氢" },
  ],
  "links": [
    { "source": "传送带", "target": "铁块", "value": 2},
    { "source": "传送带", "target": "齿轮", "value": 1 },
    { "source": "传送带-高速", "target": "传送带", "value": 3 },
    { "source": "传送带-高速", "target": "电磁涡轮", "value": 1 },
    { "source": "传送带-极速", "target": "传送带-高速", "value": 3 },
    { "source": "传送带-极速", "target": "超级磁场环", "value": 1 },
    { "source": "传送带-极速", "target": "石墨烯", "value": 1 },
    { "source": "磁化电浆炮", "target": "钛合金", "value": 20 },
    { "source": "磁化电浆炮", "target": "钛化玻璃", "value": 10 },
    { "source": "磁化电浆炮", "target": "超级磁场环", "value": 10 },
    { "source": "磁化电浆炮", "target": "电浆激发器", "value": 5 },
    { "source": "磁化电浆炮", "target": "处理器", "value": 5 },
    { "source": "大型采矿机", "target": "钛合金", "value": 20 },
    { "source": "大型采矿机", "target": "框架材料", "value": 10 },
    { "source": "大型采矿机", "target": "超级磁场环", "value": 10 },
    { "source": "大型采矿机", "target": "量子芯片", "value": 4 },
    { "source": "大型采矿机", "target": "光珊石", "value": 40 },
    { "source": "钢材", "target": "铁块", "value": 3 },
    { "source": "导弹防御塔", "target": "钢材", "value": 8 },
    { "source": "导弹防御塔", "target": "电动机", "value": 6 },
    { "source": "导弹防御塔", "target": "电路板", "value": 12 },
    { "source": "导弹防御塔", "target": "动力引擎", "value": 6 },
    { "source": "电弧熔炉", "target": "铁块", value: 4 },
    { "source": "电弧熔炉", "target": "石材", value:2 },
    { "source": "电弧熔炉", "target": "电路板", value: 4},
    { "source": "电弧熔炉", "target": "磁线圈", value: 2},
    { "source": "磁线圈", "target": "磁铁", value: 2},
    { "source": "磁线圈", "target": "铜块", value: 1},
    { "source": "电力感应塔", "target": "铁块", value: 2},
    { "source": "电力感应塔", "target": "磁线圈", value: 1},
    { "source": "分捡器", "target": "铁块", value: 1},
    { "source": "分捡器", "target": "电路板", value: 1},
    { "source": "分捡器-高速", "target": "分捡器", value: 2},
    { "source": "分捡器-高速", "target": "电动机", value: 1},
    { "source": "分捡器-极速", "target": "分捡器-高速", value: 2},
    { "source": "分捡器-极速", "target": "电磁涡轮", value: 1},
    { "source": "分捡器-集装", "target": "分捡器-极速", value: 2},
    { "source": "分捡器-集装", "target": "超级磁场环", value: 1},
    { "source": "分捡器-集装", "target": "处理器", value: 1},
    { "source": "高频激光塔", "target": "钢材", value: 9},
    { "source": "高频激光塔", "target": "电浆激发器", value: 6},
    { "source": "高频激光塔", "target": "电路板", value: 6},
    { "source": "高频激光塔", "target": "光子合并器", value: 9},
    { "source": "光子合并器", "target": "棱镜", value: 2},
    { "source": "光子合并器", "target": "电路板", value: 1},
    { "source": "化工厂", "target": "钢材", value: 8},
    { "source": "化工厂", "target": "石材", value: 8},
    { "source": "化工厂", "target": "玻璃", value: 8},
    { "source": "化工厂", "target": "电路板", value: 2},
    { "source": "化工厂-量子", "target": "化工厂", value: 1},
    { "source": "化工厂-量子", "target": "钛化玻璃", value: 10},
    { "source": "化工厂-量子", "target": "奇异物质", value: 3},
    { "source": "化工厂-量子", "target": "量子芯片", value: 3},
    { "source": "钛化玻璃", "target": "玻璃", value: 2},
    { "source": "钛化玻璃", "target": "钛块", value: 2},
    { "source": "钛化玻璃", "target": "水", value: 2},
    { "source": "奇异物质", "target": "粒子容器", value: 2},
    { "source": "奇异物质", "target": "铁块", value: 2},
    { "source": "奇异物质", "target": "重氢", value: 10},
    { "source": "粒子容器", "target": "电磁涡轮", value: 2},
    { "source": "粒子容器", "target": "铜块", value: 2},
    { "source": "粒子容器", "target": "石墨烯", value: 2},
    { "source": "电磁涡轮", "target": "电动机", value: 2},
    { "source": "电磁涡轮", "target": "磁线圈", value: 2},
    { "source": "电动机", "target": "铁块", value: 2},
    { "source": "电动机", "target": "齿轮", value: 1},
    { "source": "电动机", "target": "磁线圈", value: 1},
    { "source": "量子芯片", "target": "处理器", value: 2},
    { "source": "量子芯片", "target": "位面过滤器", value: 2},
    { "source": "处理器", "target": "电路板", value: 2},
    { "source": "处理器", "target": "微晶元件", value: 2},
    { "source": "微晶元件", "target": "高纯硅块", value: 2},
    { "source": "微晶元件", "target": "铜块", value: 1},
    { "source": "电路板", "target": "铁块", value: 2},
    { "source": "电路板", "target": "铜块", value: 1},
    { "source": "位面过滤器", "target": "卡西米尔晶体", value: 1},
    { "source": "位面过滤器", "target": "钛化玻璃", value: 2},
    { "source": "聚爆加农炮", "target": "钢材", value: 10},
    { "source": "聚爆加农炮", "target": "电动机", value: 8},
    { "source": "聚爆加农炮", "target": "电路板", value: 10},
    { "source": "聚爆加农炮", "target": "超级磁场环", value: 2},
    { "source": "超级磁场环", "target": "电磁涡轮", value: 2},
    { "source": "超级磁场环", "target": "磁铁", value: 3},
    { "source": "超级磁场环", "target": "高能石墨", value: 1},
    { "source": "人造恒星", "target": "钛合金", value: 20},
    { "source": "人造恒星", "target": "框架材料", value: 20},
    { "source": "人造恒星", "target": "堙灭约束球", value: 10},
    { "source": "人造恒星", "target": "量子芯片", value: 10},
    { "source": "钛合金", "target": "钛块", value: 4},
    { "source": "钛合金", "target": "钢材", value: 4},
    { "source": "钛合金", "target": "硫酸", value: 8},
    { "source": "框架材料", "target": "碳纳米管", value: 4},
    { "source": "框架材料", "target": "钛合金", value: 1},
    { "source": "框架材料", "target": "高纯硅块", value: 2},
    { "source": "堙灭约束球", "target": "粒子容器", value: 1},
    { "source": "堙灭约束球", "target": "处理器", value: 1},
    { "source": "粒子容器", "target": "电磁涡轮", value: 2},
    { "source": "粒子容器", "target": "铜块", value: 2},
    { "source": "粒子容器", "target": "石墨烯", value: 2},
    { "source": "电动机", "target": "铁块", value: 2},
    { "source": "电动机", "target": "齿轮", value: 1},
    { "source": "电动机", "target": "磁线圈", value: 1},
    { "source": "射线接收站", "target": "钢材", value: 20},
    { "source": "射线接收站", "target": "高纯硅块", value: 20},
    { "source": "射线接收站", "target": "光子合并器", value: 10},
    { "source": "射线接收站", "target": "处理器", value: 5},
    { "source": "射线接收站", "target": "超级磁场环", value: 20},
    { "source": "微型粒子对撞机", "target": "钛合金", value: 20},
    { "source": "微型粒子对撞机", "target": "框架材料", value: 20},
    { "source": "微型粒子对撞机", "target": "超级磁场环", value: 25},
    { "source": "微型粒子对撞机", "target": "石墨烯", value: 10},
    { "source": "微型粒子对撞机", "target": "处理器", value: 8},
    { "source": "卫星配电站", "target": "无线传输塔", value: 1},
    { "source": "卫星配电站", "target": "超级磁场环", value: 10},
    { "source": "卫星配电站", "target": "框架材料", value: 2},
    { "source": "无线传输塔", "target": "电力感应塔", value: 1},
    { "source": "无线传输塔", "target": "电浆激发器", value: 2},
    { "source": "电浆激发器", "target": "磁线圈", value: 4},
    { "source": "电浆激发器", "target": "棱镜", value: 2},
    { "source": "棱镜", "target": "玻璃", value: 3},
    { "source": "信号塔", "target": "无线传输塔", value: 2},
    { "source": "信号塔", "target": "钢材", value: 12},
    { "source": "信号塔", "target": "晶格硅", value: 6},
    { "source": "行星护盾发生器", "target": "钢材", value: 20},
    { "source": "行星护盾发生器", "target": "电磁涡轮", value: 20},
    { "source": "行星护盾发生器", "target": "超级磁场环", value: 5},
    { "source": "行星护盾发生器", "target": "粒子容器", value: 5},
    { "source": "战场分析基站", "target": "钢材", value: 12},
    { "source": "战场分析基站", "target": "电路板", value: 18},
    { "source": "战场分析基站", "target": "微晶元件", value: 6},
    { "source": "战场分析基站", "target": "动力引擎", value: 12},
    { "source": "动力引擎", "target": "磁线圈", value: 1},
    { "source": "动力引擎", "target": "铜块", value: 2},
    { "source": "制造台", "target": "铁块", value: 4},
    { "source": "制造台", "target": "齿轮", value: 8},
    { "source": "制造台", "target": "电路板", value: 4},
    { "source": "制造台-2", "target": "制造台", value: 1},
    { "source": "制造台-2", "target": "石墨烯", value: 8},
    { "source": "制造台-2", "target": "处理器", value: 4},
    { "source": "制造台-3", "target": "制造台-2", value: 1},
    { "source": "制造台-3", "target": "粒子宽带", value: 8},
    { "source": "制造台-3", "target": "量子芯片", value: 2},
    { "source": "粒子宽带", "target": "碳纳米管", value: 2},
    { "source": "粒子宽带", "target": "晶格硅", value: 2},
    { "source": "粒子宽带", "target": "塑料", value: 1},
    { "source": "卡西米尔晶体", "target": "钛晶石", value: 1},
    { "source": "卡西米尔晶体", "target": "石墨烯", value: 2},
    { "source": "卡西米尔晶体", "target": "氢", value: 12},
    { "source": "钛晶石", "target": "有机晶体", value: 1},
    { "source": "钛晶石", "target": "钛块", value: 3},
  ]
}
